### ISSUE TITLE
Cannot log in using your version since many many months. Please upload untracked files/commits

### ISSUE THREAD

**Issue by EvoPulseGaming** [Terohnon/RobinhoodDesktop#4]
I cannot login to my RH account using this. I had to modify a copy from a few months ago to support two factor auth. I don't know how you are using this, let alone adding new commits.

**Comment by Terohnon** [comment]
I haven't been using it to long into my Robinhood account since the API description page shut down, since I didn't want to risk getting my account banned.
https://github.com/sanko/Robinhood

I'm still developing this as a scripting platform for trading, but will likely need to hook it up to another brokerage unless Robinhood officially opens up their API.

**Comment by EvoPulseGaming** [comment]
Okay, yea I saw that repo as well. 

If I updated my pull request to your latest, would you be willing to at least accept it? That way I don't have conflicts every time I try to pull your new commits? (I've been logging into RH with my modified version over the last few months without issue, but its a risk I'm willing to take)

I'll have to completely redo my changes, as I previously had issues with NPLOT being a binary and ended up making it a submodule. Unless you are comfortable with submodules.

Also the two-factor changes for RH required a modified version of RobinhoodNet.

**Comment by Terohnon** [comment]
Yeah, it would be good to have this working as far as logging into Robinhood. I'll gladly pull in any changes you've got to fix that. 

I've got some customizations to NPlot to increase performance (it bogs down when drawing a couple years worth of stock data), and to add support for drawing multiple lines with their own independent Y axis on the same chart. I was too lazy to fork it though, since I think I applied those changes to an older version. That's why it is being included as a pre-compiled library. I'm open to pulling it in as a submodule, but I don't want to devote much time to that process right now.
